#!/bin/sh

#  nginx.sh
#  
#
#  Created by Eason Aug 15th,2016
#  This a Nginx Web Server start,stop and reload script.
#  chkconfig: - 81 81
#  Description: Nginx Web Server is a very popular web server in modern world and it is lightful and smartful
#    which it is more important in business companies.
#  processname: nginx
#  config: /etc/nginx/conf
#  pidfile: /var/run/nginx/nginx.pid
########### BEGIN INIT INFO ###############
#    Provides: Nginx Web Server           #
#    Required-start: $local_fs $network   #
#    Required-stop: $local_fs $network    #
#    Should-Start: distcache              #
#  Short-Desciption: start and stop nginx #
#    Description: Nginx Web Server        #
################# END INFO ################

#  Source function library
. /etc/init.d/functions

#  Define params for script use

nginx={NGINX-/usr/local/nginx/sbin/nginx}
prog=nginx
pidfile={PIDFILE-/var/run/nginx/nginx.pid}
lockfile={LOCKFILE-/var/lock/subsys/nginx}
RETVAL=0
STOP_TIMEOUT={STOP_TIMEOUT-5}

#  Define functions below:
start(){
    echo -n $"Starting $prog:"
    daemon --pidfile=${pidfile} $nginx $OPTIONS
    RETVAL=$?
    echo
[ $RETVAL = 0 ] && touch ${lockfile}
    return $RETVAL
}

stop(){
status -p ${pidfile} $spine > /dev/null
if [[ $? = 0 ]]
    then
    echo -n $"Stopping $prog:"
killproc -p {pidfile} -d ${STOP_TIMEOUT} $nginx
else
    echo -n $"Stopping $prog:"
    success
fi
}

reload(){
echo -n $"Reloading $prog:"
# Force LSB behaviour from killproc
LSB=l killproc -p {pidfile} $nginx -HUP
RETVAL=$?
if [ $? -eq 7 ]
    then
    failure $"nginx shutdown"
fi
}

#  Call functions in list
case $1 in
start)
    start;;
stop)
    stop;;
status)
    status -p ${pidfile} $nginx
    RETVAL=$?
;;
restart)
    stop
    start
;;
condrestart|try-restart)
if status -p ${pidfile} $nginx >&/dev/null
then
stop
fi
;;
force-reload|reload)
reload;;
*)
echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
RETVAL=2
esac
exit $RETVAL